### ISSUE TITLE
Error in console 

### ISSUE THREAD

**Issue by Faynominaal82** [RickyBhatti/DiscordAPI#5]
I get this error and i dont know what we are doing wrong:

![afbeelding](https://github.com/RickyBhatti/DiscordAPI/assets/99666882/47e0f25b-ab89-4712-bf1f-f75dcae86cc8)

![afbeelding](https://github.com/RickyBhatti/DiscordAPI/assets/99666882/5db89d8e-1e5a-440c-8464-972ed3a22af9)

Sometimes it works at once, and than after relogging it wont. I need to restart steam and then it works again.
And this is with all the players.

Hopefully you can help me out <3

Greetings

Fay

**Comment by RickyBhatti** [comment]
Hey Fay! 

Regarding the error, that's a neat error. Simply put, that should never occur unless the GetPlayerName method has been modified (So, it is no longer the default implementation). 
I've pushed a fix for this error in the latest release that you can download [here](https://github.com/RickyBhatti/DiscordAPI/releases). If it doesn't fix the error, please let me know.

The cURL error is related to your FiveM server, as it's attempting to reach out to the Steam API but is being blocked. You'd have to review your server, firewall, etc.

Thanks!

**Comment by RickyBhatti** [comment]
Due to the lack of reply, this issue will be closed. If you still have trouble with the resource, please reopen the issue or create a new one.
